### ISSUE TITLE
Demo app UI/UX fixes

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-App-Websites#179]
Acceptance criteria

- [x] Go through feedback and improve UI/UX of demo app. Try do the easiest fixes with the most impact
- [x] document any fixes not implemented in the timebox

Timebox to 2 days

3x Feedbacks here (Jack, presentation + Milica) https://github.com/Tonomy-Foundation/Tonomy-ID-Management/issues/347

**Comment by sadiabbasi** [comment]
Not implemented 
Jack:
1- We could split "Broadcasting" and "Confirmed by receiving node"(didn't understand)

milica:
1- The 3 dots on the carousel are missing
2- Theres an error when i click send payment in SIGN TRANSACTION

feedback:
J Use cases for blockchain needs to be updated
J Story for blockchain is copied from medical
S story impact should be clearer
S fake menu for use case is not clear
P We can probably have those bubbles with different sector names - games, votes, nfts, etc. could be made more specific - Accounting and DeFi would be different ? 
C coming soon instead of comming soon?
S/P add icons to the bubbles 
C the medical story does not highlight the problem enough
C does not believe that the progress is that fast
C needs the proof that this happened (transaction / VC)
S show some of the information about the trx / VC that was done. Maybe the transaction ID, how long it took etc…
